version: '3.1'
services:
  python: python:
    image: python:3.9
    volumes:
      - ./requirements.txt:/app/requirements.txt  # Mount requirements.txt
    command: pip install -r /app/requirements.txt  # Install libraries during startup
    # ... otros parámetros de configuración
  



  web:
    image: odoo:17.0

    depends_on:
      - db
    ports:
      - "8069:8069"
    volumes:
      - odoo-web-data:/var/lib/odoo
      - ./config:/etc/odoo
      - ./addons:/mnt/extra-addons
      - ./addons-customize:/mnt/extra-addons-customize
   
      

  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo 
 

volumes:
  odoo-web-data:      
 
