version: '3.1'
services:

  
  odoo_v2:
    build:
      dockerfile: dockerfile

    depends_on:
      - db_v2
      
    ports:
      - "8070:8070"
    volumes:
      - odoo-web-data:/var/lib/odoo
      - ./config:/etc/odoo
      - ./addons:/mnt/extra-addons
      - ./addons-customize:/mnt/extra-addons-customize
      - ./requirements.txt:/app/requirements.txt
  
 
   
      

  db_v2:
    image: postgres:15
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo 
 

volumes:
  odoo-web-data:      
 
